name: Main

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup jdk 17
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17

    - name: Validate gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Setup Gradle, Build, and Test
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        arguments: build --scan
        cache-read-only: false
      env:
        GRADLE_TOS_AGREE: yes

    - name: Upload Debug Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: debug-artifacts
        path: app/build/outputs/apk/debug

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-artifacts
        path: app/build/outputs/apk/release
